import { zValidator } from "@hono/zod-validator";
import { UUID } from "crypto";
import { Hono } from "hono";
import { z } from "zod";
import { getTasksByUserId, insertTask } from "../db/queries";
import { authMiddleware } from "../middlewares/auth.middleware";
import { HonoEnv } from "../types";

const createTaskSchema = z.object({
  taskId: z.string(),
  bucketId: z.string(),
  name: z.string(),
  color: z.string(),
  startDateTime: z.coerce.date(),
  endDateTime: z.coerce.date(),
  notes: z.string(),
});

export const tasks = new Hono<HonoEnv>()
  .use(authMiddleware)
  .get("/", async (c) => {
    const user = c.get("user");

    try {
      const tasks = await getTasksByUserId(user.id);
      return c.json(tasks);
    } catch (error) {
      console.error("Failed to get tasks:", error);
      return c.json({ error: "Failed to get tasks" }, 500);
    }
  })
  .post("/", zValidator("json", createTaskSchema), async (c) => {
    const body = c.req.valid("json");
    const user = c.get("user");

    try {
      const task = await insertTask({
        ...body,
        userId: user.id as UUID,
        id: "", // ID is generated by the database
      });
      return c.json(task);
    } catch (error) {
      console.error("Failed to insert task:", error);
      return c.json({ error: "Failed to insert task" }, 500);
    }
  });
